### ISSUE TITLE
storage: remove I/O operation in `RowSetBuilder`

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#110]
... and we need a new `RowSetWriter` to write what's inside builder to the disk.

**Comment by skyzh** [comment]
From my perspective, the `RowsetBuilder` should not contain any I/O related logic, and the logic like creating directory and flushing data should be moved to a separate module, maybe `RowsetWriter`? So that we won't need to create a directory even the rowset is still in memory.

_Originally posted by @zzl200012 in https://github.com/risinglightdb/risinglight/pull/492#discussion_r809098455_

> From my perspective, the `RowsetBuilder` should not contain any I/O related logic, and the logic like creating directory and flushing data should be moved to a separate module, maybe `RowsetWriter`? So that we won't need to create a directory even the rowset is still in memory.

That's something I'd like to refactor :)

In fact, all I/O is done in `flush_and_finish` for RowSetBuilder. I plan to let the caller to decide whether to write these files or not, instead of doing all I/O inside the `RowSetBuilder`.

We already have a tracking issue for that https://github.com/risinglightdb/risinglight/issues/110

_Originally posted by @skyzh in https://github.com/risinglightdb/risinglight/pull/492#discussion_r809157267_

**Comment by zzl200012** [comment]
That's fine. I will take a look this weekend.

**Comment by skyzh** [comment]
Oops, it seems that https://github.com/risinglightdb/risinglight/pull/499/ has already fixed this by introducing a RowSet writer. cc @zzl200012
