### ISSUE TITLE
storage: checksum `BlockType` in block header

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#247]
Currently, we store the `BlockType` in header of each block. Therefore, this part is not checksumed. We should get this part checksumed.

**Comment by hawkingrei** [comment]
Let me have a try!

**Comment by skyzh** [comment]
Thanks! The core logic lies in

https://github.com/risinglightdb/risinglight/blob/141a2624a527e346900a8c2d185d8176c89e460d/src/storage/secondary/block/block_index_builder.rs#L46-L75

I think we may need to change the encoding of block headers (e.g., put block type and checksum at the end?) in order to support this.

**Comment by unconsolable** [comment]
Hi, I found that the previous PR https://github.com/risinglightdb/risinglight/pull/544 has not make progress in about half a year, so I'd like to take a try.
