### ISSUE TITLE
Bug(Binder): wrong fields in query with group by.

### ISSUE THREAD

**Issue by st1page** [risinglightdb/risinglight#256]
```SQL
> create table t(id int, v1 int, v2 int, v3 int);
> explain select * from t group by id;
+----------------------------------------------------------------------------------------------+
| PhysicalProjection: exprs [InputRef #0, InputRef #1, InputRef #2, InputRef #3]               |
|   PhysicalSeqScan: table #8, columns [0, 1, 2, 3], with_row_handler: false, is_sorted: false |
+----------------------------------------------------------------------------------------------+
> explain select id from t group by id;
+-------------------------------------------------------------------------------------+
| PhysicalProjection: exprs [InputRef #0]                                             |
|   PhysicalSeqScan: table #8, columns [0], with_row_handler: false, is_sorted: false |
+-------------------------------------------------------------------------------------+
```

**Comment by skyzh** [comment]
Is `explain select * from t group by id;` a valid SQL 🤪? We should reject such SQL in our system... We can never know which v1, v2, v3 to select from the group :(

**Comment by skyzh** [comment]
IIRC, SQLite might accept such SQL and only return the first tuple of `v1, v2, v3`.

**Comment by st1page** [comment]
> Is `explain select * from t group by id;` a valid SQL zany_face? We should reject such SQL in our system... We can never know which v1, v2, v3 to select from the group :(

in PG, there will be an error 
> column "t.v1" must appear in the GROUP BY clause or be used in an aggregate function

**Comment by st1page** [comment]
so there are two issues.
1. treat the star (*) in a more general way in the binder, for example expand all columns appears in the context. same issue in #388
2. fix the wrong plan for query `select id from t group by id;` it not recognize the aggregation query correctly and does not give a Agg plan at all.
