### ISSUE TITLE
docs: add unit tests and usage examples for `PlanNode`

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#261]
https://github.com/singularity-data/risinglight/blob/main/src/optimizer/plan_nodes/mod.rs

The visitor - rewriter pattern in OOP is hard to express clearly in Rust. Therefore, we might need to add some unit tests, so that future developers can know how to use these patterns.

**Comment by wangrunji0408** [comment]
No longer needed as the visitor pattern has been removed in the new planner. 扬!
