### ISSUE TITLE
executor: LimitExecutor will panic if all chunks only have 1 element

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#264]
After https://github.com/singularity-data/risinglight/pull/263 is applied, and `next_batch` is called with:

```rust
it.next_batch(Some(1)).await
```

Limit executor panics with

```
thread 'test_disk::_limit_slt_' panicked at 'attempt to subtract with overflow', src/executor/limit.rs:13:9
```

**Comment by xxchan** [comment]
Is this fixed? I'm a little bit confused about how to reproduce this issue. Where to call `it.next_batch(Some(1)).await`?

**Comment by skyzh** [comment]
My fault. There are two ways to reproduce this:

* Change `TableScanExecutor` to return one row at a time.

https://github.com/risinglightdb/risinglight/blob/caa809667b5ccf41cceef17a6ac54fb35369680c/src/executor/table_scan.rs#L110

where we can replace `next_batch(None)` with `next_batch(Some(1))`.

```
---- disk::_limit_slt_ stdout ----
thread 'disk::_limit_slt_' panicked at 'attempt to subtract with overflow', src/executor/limit.rs:28:23
```

and meanwhile, I found that a lot of other tests failed if we return one row at a time 🤣

* I guess if we simply insert multiple one-row chunk to in-memory storage, and `select * from table limit 10`, will also reproduce this issue.

**Comment by skyzh** [comment]
When batch size == 1, all tests other than `limit` has been fixed in https://github.com/risinglightdb/risinglight/pull/504/
