### ISSUE TITLE
proposal: move jemalloc to optional feature

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#275]
We should use a feature to enable jemalloc, instead of making it default.

**Comment by rapiz1** [comment]
jemallocator doesn't support risc-v. Marking it as optional maybe facilitate compiling the project on risc-v 😯

**Comment by likg227** [comment]
> jemallocator doesn't support risc-v. Marking it as optional maybe facilitate compiling the project on risc-v 😯

In fact, it also can't be compiled on my Mac (
