### ISSUE TITLE
Fail to build on macOS.

### ISSUE THREAD

**Issue by LimingFang** [risinglightdb/risinglight#340]
Sorry but I can't run `cargo build` successfully on my Mac💻。
-------
Env:
- macOS Big Sur, version 11.5.1
- rustup: 1.24.3
- lastest commitID: d89bd5140be75379479e6afff8765c288306a895
-------
First i use **1.60.0-nightly** version to build, then:

>  failed to run custom build command for `jemalloc-sys v0.3.2`

Full output is [HERE](https://paste.ubuntu.com/p/RvyJbkKjV4/)

-----
Then i use **1.58.0-stable** version:

![image](https://user-images.githubusercontent.com/28479651/150132201-55803c97-6363-47f5-9e61-a2b34b953f63.png)

-----

On linux, i use **rustc 1.59.0-nightly**  which is ok. But **rustc 1.58.0** isn't, the error is same as macOS's stable version.

If this issue's format is not correct, i will update it ASAP.🙏

**Comment by skyzh** [comment]
Hi, we are depending on nightly rust’s specific features, so you will need Rust compiler >= 1.59.0 to compile this project.

By the way, we already have a rust-toolchain file on our root directory. If you follow our instructions, cargo should automatically pick the correct compiler for you.

**Comment by LimingFang** [comment]
> For the jemalloc error, you may try disabling the jemalloc feature.
> 
> cargo build --no-default-features

thanks for your quick reply，i‘ll try it again.😅

**Comment by LimingFang** [comment]
thanks, it works when disabling jemalloc feature😉

**Comment by wangrunji0408** [comment]
You may install jemalloc from homebrew and try again?
```
brew install jemalloc
```

**Comment by skyzh** [comment]
> You may install jemalloc from homebrew and try again?
> 
> ```
> 
> brew install jemalloc
> 
> ```

It should be built by the jemalloc crate itself? If we need to install it manually, maybe we should add it to our installation guide 😋🤪

**Comment by wangrunji0408** [comment]
I just uninstalled jemalloc from brew on my Mac and rebuilt the project again from scratch. It still succeed.
It seems not be the point. Never mind (

**Comment by LimingFang** [comment]
> I just uninstalled jemalloc from brew on my Mac and rebuilt the project again from scratch. It still succeed.
> It seems not be the point. Never mind (

So you just run following commands then done?
- `brew install jemalloc`
- `make build`

But i found `cargo build` would compile **jemalloc-sys v0.3.2** whether i `brew install jemalloc` or not, and this caused build error as before.
I could only succeed when i specified `--no-default-features` as suggested by Chi.

**Comment by LimingFang** [comment]
Fixed.
