### ISSUE TITLE
[Doc] Are there (or Will there be) any software architecture introduction? | 是否已有/会有更多关于软件架构的文档

### ISSUE THREAD

**Issue by ClSlaid** [risinglightdb/risinglight#341]
The repository now is quite tiny and portable though, yet more documents may be needed to unleash the educational means it carries.

虽然 ~~东旭 DB~~ risinglight DB 的代码量还是偏小的，但倘若有更多文档教育作用会更大。

**Comment by ClSlaid** [comment]
Oops, there will be docs in late February as is said in #317. I'll close this issue...

**Comment by skyzh** [comment]
Tutorial and docs are two separate things. In tutorial, we tutor students how to build a simple OLAP database. In docs, we explain the design ideas behind RisingLight and the current status of each component. Therefore, I think your concern is a valid one. We will open another tracking issue on docs later. Stay tuned!
