### ISSUE TITLE
executor: refactor executors to split chunks using DataChunkBuilder

### ISSUE THREAD

**Issue by TennyZhuang** [risinglightdb/risinglight#348]
- [x] #349 
- [x] #466
- [x] #523 
- [x] #607
- [x] #618
- [x] #619

**Comment by skyzh** [comment]
Refactoring executors to split chunk seems like a good-first-issue. If you are interested in refactoring one of our executors, feel free to create a tracking issue!

**Comment by wangqiim** [comment]
I think it don't need introduce DataChunkBuilder to TopN. Is it right?

**Comment by skyzh** [comment]
I think we need to. TopN might produce very large chunk (e.g., offset 0 limit 10000). It's better to get it chunked, so as to make the parent executor easier to handle.

**Comment by skyzh** [comment]
I've created an issue for that.

**Comment by xxchan** [comment]
All done!
