### ISSUE TITLE
tracing: add minitrace to RisingLight

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#368]
... so that it will be easier to debug our system.

- [ ] Add log to possible places.
- [ ] Add `TraceWrapper`. When creating each executor, a `TraceWrapper` will be created over the ones that developers want to trace. The wrapper will check if the output array is the same as the schema, print the timing, etc.
- [ ] Add docs on debugging.

**Comment by skyzh** [comment]
This sounds like an easy thing to implement -- if you want to add tracing information to any of our executors, feel free to create a tracking issue and start working on it.

**Comment by mapleFU** [comment]
`The wrapper will check if the output array is the same as the schema`. What do you mean by array here? @skyzh

**Comment by skyzh** [comment]
Every executor will produce a data chunk (which contains several arrays of different types). We can check if it is consistent with the schema from plan node.

**Comment by mapleFU** [comment]
Emm... So it's more like a debug tool when developing risinglight, rather than a runtime tracing tool? And I need to adding some tracing like:
1. spend time
2. some detail of chunks
3. ...

Did I catch it? @skyzh

**Comment by skyzh** [comment]
Exactly, and all of them can be done easily with the tracing ecosystem.

* spend time -- we can use `tracing_futures::Instrument` to instrument the executors and their time spent
* detail of chunks -- `tracing::event`

**Comment by mapleFU** [comment]
Ok, got it, @skyzh Let me pickup this issue, I'll try to add it this weekend.

**Comment by skyzh** [comment]
cc @WindowsXp-Beta will take a look at this.
