### ISSUE TITLE
storage: remove `async_trait` and manually expand return-position `Future`

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#389]
So that we can have lower overhead when calling `.next_batch`!

You can find some useful snippets from [skyzh's blog](https://www.skyzh.dev/posts/articles/2022-01-31-gat-async-trait/)

- [x] #392
- [x] #393
- [x] #395
- [x] #394
- [x] `TxnIterator` trait https://github.com/risinglightdb/risinglight/pull/391

**Comment by TennyZhuang** [comment]
I'd like to try it.
