### ISSUE TITLE
executor: support `TopN`

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#404]
When running TPC-H queries, it is possible that we have `limit` with `order by`. We can optimize this into `TopN`.

- [ ] add `TopN` executor. Simply create a new executor in https://github.com/risinglightdb/risinglight/tree/main/src/executor and add unit tests. The TopN executor should consume chunks from children, find topN of a column, and return the full row to the parent executor. Note that by saying top N, it means that top offset .. limit items.
- [ ] add optimization rules to rewrite `limit + order by` to `TopN`. We will need to add new plan nodes in https://github.com/risinglightdb/risinglight/tree/main/src/optimizer.

**Comment by TennyZhuang** [comment]
The [binary-heap-plus](https://crates.io/crates/binary-heap-plus) crate may be helpful to the issue with the comparator-api support.

**Comment by skyzh** [comment]
> The [binary-heap-plus](https://crates.io/crates/binary-heap-plus) crate may be helpful to the issue with the comparator-api support.

That's cool! I originally thought that we might need to hand-write a binary heap as in MergeIterator...

https://github.com/risinglightdb/risinglight/blob/a2fd396051263f5ace8c0dbb85c576f680008c00/src/storage/secondary/merge_iterator.rs#L11-L34

**Comment by xxchan** [comment]
I'd like to try this
