### ISSUE TITLE
storage: build rowset instead of buffering data when appending chunks

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#409]
Currently, when building an in-memory `ColumnMemTable` rowset,

https://github.com/risinglightdb/risinglight/blob/78caff0ef7937a0b86200cf74c6672eff6e197ee/src/storage/secondary/rowset/mem_rowset.rs#L88-L90

We simply use in-memory array builder to store information, and...

https://github.com/risinglightdb/risinglight/blob/78caff0ef7937a0b86200cf74c6672eff6e197ee/src/storage/secondary/rowset/mem_rowset.rs#L132-L144

We encode them all-at-once at the end.

This would make the ingestion process not-so-efficient. We should be able to encode the rowset when appending chunks into the `ColumnMemTable`, instead of all-at-once.

**Comment by skyzh** [comment]
This is also causing significant user experience problems when doing TPC-H benches. We may find that the progress bar of importing will always pause for about 3 secs on 256MB boundaries. It will take ~3secs to encode all data in a rowset and flush them to disk.

**Comment by zzl200012** [comment]
I'd like to have a try

**Comment by TennyZhuang** [comment]
> I'd like to have a try

Thanks for your contribution. Feel free to ask any question in our slack community!
