### ISSUE TITLE
cli: support graceful stop of txn

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#423]
Currently, we cannot cancel a query due to:

* We spawn futures over the runtime, and some channels will close after the query is terminated. This would cause problems for channel send.
* When we drop a future, we will drop the transaction object without aborting or committing.

Therefore, we should refactor parts of RisingLight in order to support graceful stop of a transaction.

**Comment by arkbriar** [comment]
After #467 's merged, I think the current executors works properly on interruption.

Shall we close this issue?
