### ISSUE TITLE
executor: limit returns nothing if offset is out of bound

### ISSUE THREAD

**Issue by xxchan** [risinglightdb/risinglight#444]
Currently it returns no chunks. If instead an empty chunk is returned, the table header can be shown, which is more user-friendly. (I think this can be a good-first-issue 😄

![image](https://user-images.githubusercontent.com/37948597/153642640-b0718cf2-96fd-4336-8a66-2929957a7e63.png)

**Comment by skyzh** [comment]
I think a better solution is to make header part of the query result (instead of part of the data chunk), so that the caller can:

* `.run(sql: &str) -> (ColumnDesc, Vec<DataChunk>)`
* where the first parameter is the description of columns
* and the data chunk don't have to add a `header` field.

**Comment by xxchan** [comment]
I agree! Then do we rename this issue or.create a new issue？

**Comment by skyzh** [comment]
> I agree! Then do we rename this issue or.create a new issue？

We already have one 🥳😇 https://github.com/risinglightdb/risinglight/issues/435
