### ISSUE TITLE
cli: don't panic on bind error.

### ISSUE THREAD

**Issue by zbtzbtzbt** [risinglightdb/risinglight#448]
![image](https://user-images.githubusercontent.com/35688959/153718955-d6337c91-72d5-4f1b-8b70-cb206ce014e9.png)

we can hint `parse error:xxx` like other databases.

**Comment by xxchan** [comment]
Actually  this is a PostgreSQL-specific statement `SHOW <variable>`, not show tables. 

![image](https://user-images.githubusercontent.com/37948597/153720301-1b26d874-9d14-4ca3-8fa2-2e9eb361ca79.png)

**Comment by skyzh** [comment]
Oops, it turns out that only MySQL supports `show tables`. For Postgres, we can only use `\dt` to list tables. Therefore, I think it's better to warn users that `show xxx` is not supported. At the same time, we should not panic in case of such error. We should only show an error on screen.

**Comment by zbtzbtzbt** [comment]
> 



> Oops, it turns out that only MySQL supports `show tables`. For Postgres, we can only use `\dt` to list tables. Therefore, I think it's better to warn users that `show xxx` is not supported. At the same time, we should not panic in case of such error. We should only show an error on screen.

good idea
