### ISSUE TITLE
optimizer: table scan schema should include row handler

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#450]
Currently, the implementation of TableScan's schema is not correct.

https://github.com/risinglightdb/risinglight/blob/c221b085ceb4a61fe1cf1e6c9d6caa36b7215a2e/src/optimizer/plan_nodes/logical_table_scan.rs#L75-L77

When `with_row_handler` is enabled, we should have an extra i64 column for row handlers at the end.

**Comment by xuyifangreeneyes** [comment]
Can I have a try on this?

**Comment by skyzh** [comment]
Thanks! By the way, currently there are no way to test if an executor's schema is consistent with its data chunk outputs. If you want, you may also have a look at https://github.com/risinglightdb/risinglight/issues/430.
