### ISSUE TITLE
storage: remove filter scan functionality on column iterator

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#452]
In column iterator, we have implemented...

https://github.com/risinglightdb/risinglight/blob/c221b085ceb4a61fe1cf1e6c9d6caa36b7215a2e/src/storage/secondary/column/concrete_column_iterator.rs#L137-L141

This function will only have effect (reduce I/O) when a single call of `next_batch` spans across multiple blocks. However, this is a very rare case.

ColumnIterator is used by RowSetIterator. In RowSetIterator, we already have a very fine-grained control of how many rows to scan:

https://github.com/risinglightdb/risinglight/blob/c221b085ceb4a61fe1cf1e6c9d6caa36b7215a2e/src/storage/secondary/rowset/rowset_iterator.rs#L102-L120

Column iterators' fetch hint is simply remaining items of the current block. Therefore, we seldom perform a single `next_batch` call across multiple blocks.

Therefore, we can solely leverage `next_batch` (w/o filter map) and `skip` to perform filter scan on columns. We call `.skip` only when the computed filter bitmap is all 0.

- [ ] refactor RowSetIterator to never use visibility map on column
- [ ] set fetch size to `min(expected_size, fetch_size)`. (Currently the table scan executor only calls `next_batch` with None. But we should prepare for future cases.)
  * We can also call `next_batch` multiple times until we reach `expected_size`. Not important.
- [ ] remove `next_batch_with_filter` on `ColumnIterator`.

cc @likg227 any ideas?

**Comment by skyzh** [comment]
Exactly as what I think. You may take this if you want. Thanks!

**Comment by likg227** [comment]
Good idea! Can't wait to see your contribution!
