### ISSUE TITLE
cli: output table is splitted

### ISSUE THREAD

**Issue by xxchan** [risinglightdb/risinglight#456]
not elegant
```
> create table x (x int)
created
> insert into x values (1)
1 rows inserted
> insert into x values (2)
1 rows inserted
> insert into x values (33333)
1 rows inserted
> select * from x;
+---+
| x |
+---+
| 1 |
+---+
+---+
| 2 |
+---+
+-------+
| 33333 |
+-------+
```

**Comment by skyzh** [comment]
Does this happen in in-memory engine or secondary engine (or both)?

**Comment by xxchan** [comment]
Only in-memory engine.

**Comment by xxchan** [comment]
The table message is implemented in `Display` for `DataChunk`. But the output is `Vec<DataChunk>`. And currently we simply iterate the vec and print each chunk. So if there are multiple chunks in the result, the table will be splitted.

```rust
// in main.rs
for chunk in chunks {
    print_chunk(&chunk)
}

// in db.rs
output[0].set_header(column_names);
```

**Comment by skyzh** [comment]
It seems that we should merge chunks together in `main.rs` before printing them out... As we don't expect users to use cli to print large amount of information, I think it's reasonable to do the fix.

**Comment by xiaoyong-z** [comment]
i will try this
