### ISSUE TITLE
executor: refactor expression framework to return `Arc<ArrayImpl>`

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#464]
When grouping by a key, the group expr will be an `InputRef`.

https://github.com/risinglightdb/risinglight/blob/52994366ebcd09047a798d4e452a1989a8568697/src/executor/hash_agg.rs#L31-L33

https://github.com/risinglightdb/risinglight/blob/f75c99bb274dece4215a4ba0cc1b60ff1ab796b8/src/executor/evaluator.rs#L16

And evaluating an `InputRef` will clone the whole Array, which is not efficient.

As this is a common case to solely evaluate an `InputRef`, we can optimize this by changing the expression eval return type to `Arc<ArrayImpl>`.

**Comment by wangrunji0408** [comment]
How about making `ArrayImpl` cheaply clonable (like `bytes::Bytes`)? In other words, put `Arc` inside the array.

**Comment by skyzh** [comment]
> How about making `ArrayImpl` cheaply clonable (like `bytes::Bytes`)? In other words, put `Arc` inside the array.

Good idea. It is designed to be immutable, so it's okay to wrap an Arc inside.

**Comment by kwannoel** [comment]
Would like to take this up!

**Comment by kwannoel** [comment]
Are there any benchmarks you would recommend to demonstrate greater efficiency? Thanks!

**Comment by kwannoel** [comment]
> > How about making `ArrayImpl` cheaply clonable (like `bytes::Bytes`)? In other words, put `Arc` inside the array.
> 
> Good idea. It is designed to be immutable, so it's okay to wrap an Arc inside.

And to clarify is this what you're talking about?
```rs
pub struct ArrayImpl {
    inner: Arc<ArrayImplInner>, // Wrap with Arc, cheap to clone
}

impl ArrayImpl {
    pub fn new(&self, inner: Arc<ArrayImplInner>) -> Self {
        ArrayImpl {inner}
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum ArrayImplInner {
    Bool(BoolArray),
    // Int16(PrimitiveArray<i16>),
    Int32(I32Array),
    Int64(I64Array),
    // Float32(PrimitiveArray<f32>),
    Float64(F64Array),
    Utf8(Utf8Array),
    Blob(BlobArray),
    Decimal(DecimalArray),
    Date(DateArray),
    Interval(IntervalArray),
}
```

**Comment by skyzh** [comment]
> Are there any benchmarks you would recommend to demonstrate greater efficiency? Thanks!

I'd prefer `select column from table` in memory. Maybe we can copy this e2e test case, and change the query to `select v1 from table`. Currently, `select v1 from table` involves one clone. After this issue gets resolved, I think there will probably be some improvement (not guaranteed 🤣) 

https://github.com/risinglightdb/risinglight/blob/848555399a1a13ab250f9de33b3c93b3a3ed096a/benches/e2e.rs#L53-L76

> And to clarify is this what you're talking about?

That's exactly what I'm thinking about! Indeed, we can define `ArrayImpl` like:

```
#[derive(Clone)]
pub struct ArrayImpl(Arc<ArrayImplInner>);
```

But note that this might involve some re-work of 

https://github.com/risinglightdb/risinglight/blob/848555399a1a13ab250f9de33b3c93b3a3ed096a/src/array/mod.rs#L230-L232

Some `From` and `Into` implementation might need to be changed to make everything compile.

If you have any question, don't hesitate to leave a comment here or ping me on community Slack. Thanks for your contribution!

**Comment by kwannoel** [comment]
What about placing wrapping `Arc` around fields?
```rs
pub enum ArrayImpl {
    Bool(Arc<BoolArray>),
    // ...
}
```

Reason being there's quite a few areas which do pattern matching around `ArrayImpl` constructors. This way the pattern matching for ArrayImpl can still be preserved.

**Comment by skyzh** [comment]
As long as we can make `ArrayImpl`'s Clone cheap, we can wrap `Arc` anywhere. Wrapping it inside `ArrayImpl` also sounds like a good idea!

**Comment by kwannoel** [comment]
Alright, have written a [small prototype for `ArrayImpl::Bool`](https://github.com/risinglightdb/risinglight/pull/577) which compiles (but don't run it because there are placeholder `loop{}` ).

The steps to implement this approach are as follows:
1. Refactor all `ArrayImpl` fields to be wrapped in `Arc`.
    ```rs
    pub enum ArrayImpl {
        Bool(Arc<BoolArray>),
        // refactor rest of enum constructors
    }
    ```

1. Create smart constructors so we don't have to write `ArrayImpl::Bool(Arc::new(...))` and can just do `ArrayImpl::new_bool`.
    This also means we have to distinguish between 2 cases:
    1. Instantiating on new values -> use smart constructors (e.g. `ArrayImpl::new_bool`)
        ```rs
            Self::Int32(a) => match data_type {
                Type::Boolean => Self::new_bool(unary_op(a, |&i| i != 0)),

        ```
    1. When we can just clone -> just use enum constructors (e.g. `ArrayImpl::Bool`)
        ```rs
            Self::Bool(a) => {
                match data_type {
                    Type::Boolean => Self::Bool(a.clone()),
        ```
1. Update call-sites for instantiation of `ArrayImpl`, **depending on which of the above two cases it is**.
1. Finally update macros in `src/array/mod.rs` as well, once everything is wrapped in `Arc`.

**Comment by skyzh** [comment]
Thanks for your work, that sounds good! I also left some comments in the PR.
