### ISSUE TITLE
cli: print query time

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#471]
After running each query, the cli should print a line of how much time it takes. For example:

```
create table t1(v1 int not null);
created
in 3.0s
```

We can only print out time in interactive shell mode. So the only place to change is:

https://github.com/risinglightdb/risinglight/blob/6ff143ed6d4555318886284a9c7ad4b0e7d70f0f/src/main.rs#L74-L81

**Comment by tabVersion** [comment]
I will work on this.
