### ISSUE TITLE
tests: small change in `tests` folder will cause a full rebuild of binary

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#472]
Cause by https://github.com/risinglightdb/risinglight/pull/376

Is there any way that `build.rs` only detects only file name instead of full file content?

**Comment by arkbriar** [comment]
According to [cargo: change detection of build script](https://doc.rust-lang.org/cargo/reference/build-scripts.html#change-detection), re-run of build scripts only relies on the modification of filesystem "last-modified" timestamp.

To avoid re-run each time when only file content changes, we can manually maintain a list of the test cases (filenames) in a single file instead and declare it as the trigger.

**Comment by skyzh** [comment]
Good idea!

**Comment by skyzh** [comment]
... so we can create a "test_cases.rs", which includes a function, and `include!("tests/test_cases.rs")` in `build.rs`?

Meanwhile, in the rerun-if-changed config, we can only specify `test_cases.rs` as dependency.

**Comment by arkbriar** [comment]
> ... so we can create a "test_cases.rs", which includes a function, and `include!("tests/test_cases.rs")` in `build.rs`?
> 
> Meanwhile, in the rerun-if-changed config, we can only specify `test_cases.rs` as dependency.

What is the function in "test_cases.rs" for? If it's for scanning the dir, the build script can not be triggered when there're modifications in `tests/sql`. 

IMO only a list of file names is needed. Developers should maintain the list whenever a test file is added or removed.

Besides, we can add a check on the list to make sure all files are included (and no non-existing files).

**Comment by skyzh** [comment]
You're right. Ignore my comments above 🤪

**Comment by skyzh** [comment]
Then I think a better approach is to:

* maintain a list of files in a vector in `test_cases.rs`, and generate the corresponding test case functions.
* check if all files matching the filename pattern are included.

cc @wangrunji0408

**Comment by xxchan** [comment]
I'm a little bit confused: if we need to maintain a list of files now, what's the difference from the situaion before the auto discovery?

**Comment by skyzh** [comment]
That's true... Maybe we should find another way to do auto-discovery of tests...
