### ISSUE TITLE
cli: support multi-line interactive mode

### ISSUE THREAD

**Issue by xiaoyong-z** [risinglightdb/risinglight#475]
If i run the following sql line by line without ";", then the  history.txt will not contain ";". It is not convient for me to copy the scripts from history.txt to the cli and run them together, as i need to add the ";" at the end of all sql sentence.
 
```
> create table x (x int)
> insert into x values (1)
> insert into x values (2)
> insert into x values (33333)
> select * from x
```

The history file:
```
create table x (x int)
insert into x values (1)
insert into x values (2)
insert into x values (33333)
select * from x;
```

**Comment by skyzh** [comment]
Normally, the shell should not execute a SQL until there is a ;. I think we'd better refactor the interactive shell?

**Comment by xxchan** [comment]
Usually history file records user input as is, including incorrect input. So I'm not sure whether adding `;` is proper...

> Normally, the shell should not execute a SQL until there is a ;

I found https://github.com/dbcli/mycli supports both Multi-line mode and the eager mode allowing no `;` (default). I think we should choose one style for now? One-line is simpler but multi-line is more traditional?

**Comment by TennyZhuang** [comment]
> Normally, the shell should not execute a SQL until there is a ;. I think we'd better refactor the interactive shell?

Pgwire doesn’t require a semicolon, so pgcli will accept sql without semicolon, but psql requires it.

**Comment by skyzh** [comment]
Then I would prefer keep it as-is in our current cli. A multi-line mode can be configured via cli parameter. 🥰

**Comment by cs50Mu** [comment]
can anyone elaborate the a little bit? I want to have a try. My current understanding is as follows:

the interactive shell currently doesn't support multi-line sql without the ending semicolon, eg,

```
select 1
select 2
select 3
```
which gives the following error:

`parse error: sql parser error: Expected end of statement, found: select`

and we want to support this kind of input

**Comment by skyzh** [comment]
I think we support it -- did you just past those three lines into the console? If you press enter without semicolon, the current shell would proceed to evaluate the statement.

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/4198311/160826884-a21a25cd-fd5e-4b82-8e5b-a800454a4231.png">

But in Postgres shell:

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/4198311/160826992-cf2c7d16-1f3f-4cec-9fdf-3991893e1d53.png">

**Comment by skyzh** [comment]
If we want to correctly handle all cases... do we need to have a simple lexer on cli? Then it doesn't seem like a good first issue 🤣

**Comment by skyzh** [comment]
But we can keep it simple for now -- we don't need to handle the case like we have `;` in string. We can simply detect if the last character of an input line is `;`?

**Comment by cs50Mu** [comment]
> I think we support evaluate on enter -- did you just past those three lines into the console? If you press enter without semicolon, the current shell would proceed to evaluate the statement.
> 
> <img alt="image" width="1119" src="https://user-images.githubusercontent.com/4198311/160826884-a21a25cd-fd5e-4b82-8e5b-a800454a4231.png">
> 
> But in Postgres shell:
> 
> <img alt="image" width="1119" src="https://user-images.githubusercontent.com/4198311/160826992-cf2c7d16-1f3f-4cec-9fdf-3991893e1d53.png">

yes, one line without the semicolon is ok, I thought your want to run three line together with the  semicolon....

**Comment by skyzh** [comment]
> run three line together with the semicolon....

This should also be supported now! What we need is to run one statement that spans multiple lines 🤪

**Comment by skyzh** [comment]
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/4198311/160829555-b545e67b-4902-4cd9-82dc-9da976143795.png">

**Comment by Gun9niR** [comment]
What prompt should we use for lines other than the first line？

**Comment by skyzh** [comment]
Of course. We can execute sql only when we meet ;, as long as it's the last character.
