### ISSUE TITLE
binder: plan not optimal for count(*) with filter

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#482]
```
PhysicalProjection: exprs [InputRef #0]
  PhysicalSimpleAgg: 1 agg calls
    PhysicalTableScan: table #9, columns [0], with_row_handler: true, is_sorted: false, expr: Gt(InputRef #0, Int32(5) (const))
```

The plan is not optimal. As we already have column 0 scanned, we don't need row handler.

We can refine the binder logic later to handle this case, and get this PR merged at first. Thanks!

_Originally posted by @skyzh in https://github.com/risinglightdb/risinglight/pull/447#discussion_r807561493_

**Comment by skyzh** [comment]
Looks better like a task for optimizer... Only optimizer knows how many columns will be read indeed.

**Comment by xxchan** [comment]
copy some comments🤪
> By the way, I'm thinking of moving row-handler related logics to the optimizer... For example, if column pruning found that there's no column to scan, we automatically attach a row handler to the table.
>
> At the same time, if our queries become more and more complex, it won't be possible for us to enumerate all rules to add row_handler column, solely in the planner... I don't have a clear idea about that, but I think we will eventually (1) make row_handler a real logical column instead of a flag for table (2) use the optimizer rule to decide whether to scan the row handler column.

_Originally posted by @skyzh in https://github.com/risinglightdb/risinglight/pull/502#pullrequestreview-887911808_
