### ISSUE TITLE
storage: store `column_iterators` without `Option`

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#483]
https://github.com/risinglightdb/risinglight/blob/8464ae49879b2745f31674dcda43caefd42c86fd/src/storage/secondary/rowset/rowset_iterator.rs#L22

Currently, we are storing `column_iterators: Vec<Option<ColumnIteratorImpl>>`. After some refactors recently, we will fill the vector will all `Some`. So we can safely remove the `Option` here.

**Comment by Fedomn** [comment]
I will take this
