### ISSUE TITLE
storage: improve flush logging

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#495]
Currently, the log is like:

```
RowSet  flushed, DV #1(RS10),#2(RS9),#3(RS8),#4(RS7) flushed
6001215 rows deleted
```

There are two spaces between "RowSet" and "flushed", due to no RowSet gets flushed.

We should hide the "RowSet  flushed" part if nothing gets flushed.

**Comment by kwannoel** [comment]
Would like to take a shot at this!
