### ISSUE TITLE
storage: using variable size encoding for RLE count

### ISSUE THREAD

**Issue by ludics** [risinglightdb/risinglight#531]
Currently, we use u16 for the count of run-length encoding:
https://github.com/risinglightdb/risinglight/blob/613ffb6990458bb3558b923ce77ea1e3c1dced4a/src/storage/secondary/block/rle_block_builder.rs#L16-L26

Also we can consider using variable size encoding (IIRC, prost::encode_varint?) for those integers, and therefore we can store elements more efficiently, and we don't need to limit the RLE count to u16. This could be done in the future; I'm not sure if we can optimize storage space by using variable size encoding for RLE count.

_Originally posted by @skyzh in https://github.com/risinglightdb/risinglight/pull/507#discussion_r811545436_

**Comment by unconsolable** [comment]
Seems it has been resolved by #666 @skyzh
