### ISSUE TITLE
Group by panics

### ISSUE THREAD

**Issue by xxchan** [risinglightdb/risinglight#539]
This reports error
```sql 
> SELECT c0+2 FROM t1 GROUP BY c0+1; 
logical plan error: (Column #ColumnRefId { database_id: 0, schema_id: 0, table_id: 2, column_id: 0 } + 2) must appear in the GROUP BY clause or be used in an aggregate function
```
But this panics
```sql
> SELECT c0+2+count(*) FROM t1 GROUP BY c0+1; 
thread 'tokio-runtime-worker' panicked at 'Column #ColumnRefId { database_id: 0, schema_id: 0, table_id: 2, column_id: 0 } should not be evaluated in `eval_array`', src/executor/evaluator.rs:55:18
```

And this (similar to https://github.com/risinglightdb/risinglight/issues/501, maybe fixed by https://github.com/risinglightdb/risinglight/discussions/503)
```sql
> select c0*1 from t1 group by c0*1
+----+
| c0 |
+----+
| 3  |
| 1  |
+----+
in 0.004s
> select c0*0 from t1 group by c0*0
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', src/optimizer/plan_nodes/logical_projection.rs:66:25
```

_Originally posted by @xxchan in https://github.com/risinglightdb/risinglight/pull/535#issuecomment-1055257700_

**Comment by skyzh** [comment]
There will be more and more edge cases after we support subquery... may need a better design ahead of implementation for new PRs.

**Comment by skyzh** [comment]
I guess now it won't panic, but will only report an error. Let's get this issue closed.
