### ISSUE TITLE
installation with `cargo build` is super slow

### ISSUE THREAD

**Issue by dengn** [risinglightdb/risinglight#541]
Tried to install risinglight, `cargo build` never succeeded. It appears to be a networking issue. I have a global VPN well set up. 

<img width="964" alt="image" src="https://user-images.githubusercontent.com/4965857/156307214-350b15dc-a518-4030-a5b9-7b667b691ab7.png">

**Comment by skyzh** [comment]
Doesn't look like a problem with RisingLight project itself. This docs may help https://github.com/risinglightdb/risinglight/blob/main/docs/00-develop.md
