### ISSUE TITLE
cargo run with a bus error 

### ISSUE THREAD

**Issue by dengn** [risinglightdb/risinglight#542]
risinglight is well installed. But when trying to launch the SQL shell, `cargo run` ends with a bus error. 
<img width="439" alt="image" src="https://user-images.githubusercontent.com/4965857/156308584-4bc2774b-aa2f-4cb4-a1f6-5944a0ea36d5.png">

**Comment by xxchan** [comment]
Can you try `valgrind cargo run`? (I'm not sure)

**Comment by dengn** [comment]
> Can you try `valgrind cargo run`? (I'm not sure)

With a Big Sur 11.4, it seems that `valgrind` is not an easy option.
https://github.com/LouisBrunner/valgrind-macos/issues/19

<img width="468" alt="image" src="https://user-images.githubusercontent.com/4965857/156313677-bf845548-d422-4177-9ee5-1c1d8ecacee6.png">

**Comment by xxchan** [comment]
What about `gdb target/debug/risinglight`?
