### ISSUE TITLE
optimizer: mapping `InputRef` when pruning columns

### ISSUE THREAD

**Issue by xxchan** [risinglightdb/risinglight#547]
When pruning columns, we need to map `InputRef`. 

e.g., pruning
```text
Filter(cond: input_ref(1)<5)
  TableScan(v1, v2, v3)
```
with required columns `[2]` will result in
```text
Filter(cond: input_ref(0)<5)  # 1->0
  TableScan(v2, v3)
```

Currently we shifted them (subtract each one with an offset), which turns the smallest one into `0`: https://github.com/risinglightdb/risinglight/pull/543/files#diff-eb434564a52231d1f4486e36fdab58dc83a6709af14dc87554def86bdc4ecfe9R66-R76 

But shift is not enough: inconsecutive input refs `[1,3]` should become `[0,1]`. But since we don't have sub-queries like `select v1, v2 from (select v1,v3 from t)`, this is hard to trigger.

_Originally posted by @xxchan in https://github.com/risinglightdb/risinglight/pull/543#r818370427_

**Comment by XieJiann** [comment]
I wanna try it : )

**Comment by XieJiann** [comment]
> I think it is not needed, because filter's schema is just the same as its child. And we recursively pruned the child, so filter will behave correctly.

emmmmm, I think the child's schema may not equal to `required_columns`?
e.g.,
```
Join(v1, v2)
   Filter(v3 > 1)
     Get(v1, v2, v3)
```
The filter's `required_schema` is v1, v2. And it's child's schema is v1, v2, v3

**Comment by xxchan** [comment]
Do you mean `filter.prune_col(required_cols)` will requires more than `required_cols` for its children? Actually this is already handled when we call `child.prune_col(visitor.0)`. 

I'm not sure if I understood your question correctly, please let know if it isn't the case or if you have any other questions. 😄

**Comment by xxchan** [comment]
Oh yes, you are right!! So my example should be corrected: 😲

```
# prune, requireding input_ref(2), which is v3

Filter(cond: input_ref(1)<5)
  TableScan(v1, v2, v3)

-> 

Project(expr0=input_ref(1))
  Filter(cond: input_ref(0)<5)  # 1->0
    TableScan(v2, v3)
```

Could you please help fix the rule and the test?

**Comment by XieJiann** [comment]
> Oh yes, you are right!! So my example should be corrected: 😲
> 
> ```
> # prune, requireding input_ref(2), which is v3
> 
> Filter(cond: input_ref(1)<5)
>   TableScan(v1, v2, v3)
> 
> -> 
> 
> Project(expr0=input_ref(1))
>   Filter(cond: input_ref(0)<5)  # 1->0
>     TableScan(v2, v3)
> ```
> 
> Could you please help fix the rule and the test?

Okk, I'll fix it

**Comment by XieJiann** [comment]
Another question, the content of `required_columns`  is `column_id` or `column index`?

In `src/optimizer/plan_nodes/logical_filter.rs` loc 170, it store the `column_id`
However, in the `src/optimizer/plan_nodes/mod.rs` 146, it means the `column_idx`

And the `column_id` and `column_idx` are different in `src/optimizer/plan_nodes/logical_filter.rs` test, where the column id is [1,2,3] and column idx is [0,1,2]
