### ISSUE TITLE
Storage bootstrap error

### ISSUE THREAD

**Issue by BaymaxHWY** [risinglightdb/risinglight#552]
```
Finished dev [unoptimized + debuginfo] target(s) in 0.57s
Running `target/debug/risinglight -f tests/sql/basic_test.slt`
2022-03-07T12:37:52.264327Z  INFO risinglight: using Secondary engine
2022-03-07T12:37:52.269119Z  INFO risinglight::storage::secondary::storage: applying 9 manifest entries
2022-03-07T12:37:52.269753Z  INFO risinglight::storage::secondary::storage: 0 tables loaded, 3 rowset loaded, 0 DV loaded
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/hwy/Code/Rust/risinglight/src/storage/secondary/storage.rs:131:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This error occurs when `cargo run -- -f tests/sql/basic_test.slt` is run the second time

The code snippet for specifying the bug looks like this
```rust
// risinglight/src/storage/secondary/storage.rs:131
  for (_, entry) in rowsets_to_open {
            let table = tables.get(&entry.table_id).unwrap(); // error panic
            let disk_rowset = DiskRowset::open(
                table.get_rowset_path(entry.rowset_id),
                table.columns.clone(),
                engine.block_cache.clone(),
                entry.rowset_id,
                options.io_backend,
            )
            .await?;
            changeset.push(EpochOp::AddRowSet((entry, disk_rowset)));
        }
```
There are no **tables** after reading the **manifest** file, but there are **rowsets**, I tried to use `match` to handle `None`, and the error didn't recur.

If this is a bug, can I submit a PR to fix it? (I am a rust novice

**Comment by skyzh** [comment]
The underlying cause behind this panic is because that we didn't support drop table. Here I think it's okay to simply continue the for loop if the table doesn't exist. Welcome to send a PR!

**Comment by skyzh** [comment]
I've also created a tracking issue for supporting drop table. If you are interested in fixing the root cause (instead of work-around), you may also start working on this issue https://github.com/risinglightdb/risinglight/issues/553. Thanks!

**Comment by BaymaxHWY** [comment]
Yeah, I'd love to. Thanks for answering so quickly(God Chi !)
