### ISSUE TITLE
storage: delete RowSets when drop table

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#553]
Currently, when we call `drop table`, the RowSets don't get deleted. Considering we don't expect to support multi-thread DDL for now, we can simply change the process of drop table.

https://github.com/risinglightdb/risinglight/blob/53ccdf96f36267c4703386577eeeff1da18bdf13/src/storage/secondary/manifest.rs#L239-L250

When dropping table, we should also scan all RowSets belong to the table, and apply `DeleteRowSet` and `DeleteDV` changes. Therefore, we won't have problem recovering from a database where a table gets created then dropped.

**Comment by BaymaxHWY** [comment]
hai, i can't find one struct that hold a mapping between table_id and rowset_id or dv_id, "scan all RowSets belong to the table", can only go through the storage directory to get the mapping?

**Comment by skyzh** [comment]
You may first call `self.version.pin_version` to get a latest snapshot of the table, then get all rowsets belonging to this table, and finally delete them by notifying the vacuumer. No need to manually `delete` or `iterate` the folder by ourselves.

Another way to achieve is to modify the meaning of `DropTable` manifest entry. By calling `DropTable`, we can assume all rowsets belonging to that table are all deleted. Then we may need to change the recovery process and the vacuumer to ignore / delete rowsets if a table gets dropped.

Both approaches are okay. You may choose the one you want.
