### ISSUE TITLE
Tracking: publish to crates.io

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#574]
Currently, we are using many crates that are installed from git. We need to switch to a published crates.io version before we can publish RisingLight to crates.io.

**Comment by xxchan** [comment]
- sqllogictest: no problem
- sqlparser: our fork made a change: https://github.com/risinglightdb/sqlparser-rs/commit/edead1b
- futures_async_stream: not sure why a commit is used (from #271)

**Comment by skyzh** [comment]
The latest published version of futures-async-stream has different interface from its main branch... so we may wait for the upstream to get things published.

**Comment by xxchan** [comment]
So how to handle `sqlparser`? Do we send PR to upstream or publish fork? cc @wangrunji0408

**Comment by wangrunji0408** [comment]
I'd like to push it upstream. Let me take this.
