### ISSUE TITLE
storage: remove `Arc` from `Arc<ArrayImpl>`

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#580]
After https://github.com/risinglightdb/risinglight/issues/464 refactor has been completed, we can remove some prior optimizations in storage crate!

https://github.com/risinglightdb/risinglight/blob/5708a8e2f1d72dd5e7db3c3fb5b93f5c59c348e6/src/storage/chunk.rs#L18-L27

Now `ArrayImpl` has an `Arc` inside, so we can safely change the `Arc<ArrayImpl>` to `ArrayImpl` in storage chunk with cheap clones.

**Comment by kwannoel** [comment]
Would like to take this up
