### ISSUE TITLE
storage: support composite sort key in MergeIterator

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#588]
Currently, `MergeIterator` only supports taking a single `sort_idx` as parameter:

https://github.com/risinglightdb/risinglight/blob/7c5e0d5193708c50b14c98f3efdddfcefbe445cd/src/storage/secondary/merge_iterator.rs#L34-L36

We should make `MergeIterator` be able to accept a vector of `sort_idx`. For example, `sort_key_idx = [2, 1, 0]`:

* Implies that the child iterators are already being sorted using 3 columns: firstly be column `#2`, then by column `#1`, at last by `#0`.
*MergeIterator should also sort by this rule.

```rust
pub fn new(iters: Vec<SecondaryIterator>, sort_key_idx: Vec<usize>) -> Self {
```

After we finish the refactor in the storage layer, we can firstly make all places to pass `vec![sort_key]` instead of `sort_key`. Then, we can refactor little by little to support full composite sort key support across our system.

**Comment by BaymaxHWY** [comment]
Hi, can i try this? This requirement just changes the code about `sort_key_idx` and the function `compare_data()`?
