### ISSUE TITLE
cargo build fail when using prost-build v0.10.0

### ISSUE THREAD

**Issue by D2Lark** [risinglightdb/risinglight#615]
> ark@DESKTOP-6IK6QE9:~/rust/workdir/risinglight$ cargo build
>     Blocking waiting for file lock on package cache
>     Blocking waiting for file lock on package cache
>     Blocking waiting for file lock on package cache
>    Compiling prost-build v0.10.0
> error: failed to run custom build command for `prost-build v0.10.0`
> 
> Caused by:
>   process didn't exit successfully: `/home/ark/rust/workdir/risinglight/target/debug/build/prost-build-d876dd49a6c2b336/build-script-build` (exit status: 101)
>   --- stdout
>   cargo:rerun-if-changed=/home/ark/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.0/third-party/protobuf/cmake
>   CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
>   CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
>   HOST_CMAKE_TOOLCHAIN_FILE = None
>   CMAKE_TOOLCHAIN_FILE = None
>   CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
>   CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
>   HOST_CMAKE_GENERATOR = None
>   CMAKE_GENERATOR = None
>   CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
>   CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
>   HOST_CMAKE_PREFIX_PATH = None
>   CMAKE_PREFIX_PATH = None
>   CMAKE_x86_64-unknown-linux-gnu = None
>   CMAKE_x86_64_unknown_linux_gnu = None
>   HOST_CMAKE = None
>   CMAKE = None
>   running: "cmake" "/home/ark/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.0/third-party/protobuf/cmake" "-DCMAKE_INSTALL_PREFIX=/home/ark/rust/workdir/risinglight/target/debug/build/prost-build-51a608bbc87e5e85/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"
> 
>   --- stderr
>   thread 'main' panicked at '
>   failed to execute command: Permission denied (os error 13)
> 
>   build script failed, must exit now', /home/ark/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.48/src/lib.rs:975:5
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

After I change prost = "0.10.0" to prost = "0.9.0" in two Cargo.toml and delete Cargo.lock ,I can pass cargo build

**Comment by skyzh** [comment]
Prost-build 0.10 will build the protobuf compiler on your machine. You have two ways to solve this:

* Check your toolchain and see if there's anything wrong with cmake and C++ compilers
* Or simply `brew install protobuf` to make prost-build pick your systems' protoc

**Comment by skyzh** [comment]
I think we can also have `brew install protobuf` and `sudo apt install protobuf-compiler` in the development guide...

**Comment by D2Lark** [comment]
It seems that I lack of cmake...  Now it is fine. I used ubuntu20.04. wish to have some doc like [that](https://github.com/singularity-data/risingwave/blob/main/CONTRIBUTING.md) :)

**Comment by skyzh** [comment]
Next time for sure :)
