### ISSUE TITLE
binder: primary key should by-default be non-null

### ISSUE THREAD

**Issue by Shmiwy** [risinglightdb/risinglight#632]
```sql
create table t(a int primary key, b int);
```
will produce a  `BoundCreateTable` like this 
```
BoundCreateTable {
        database_id: 0,
        schema_id: 0,
        table_name: "t",
        columns: [
            ColumnCatalog {
                id: 0,
                desc: ColumnDesc {
                    datatype: Int(None) (null),
                    name: "a",
                    is_primary: true,
                },
            },
            ColumnCatalog {
                id: 1,
                desc: ColumnDesc {
                    datatype: Int(None) (null),
                    name: "b",
                    is_primary: false,
                },
            },
        ],
    },
```
I think we need to make primary key default not to be null, so if i type sql query above, we will make `a` not null. Or we can forbid that syntax.

the reason for this is that
https://github.com/risinglightdb/risinglight/blob/d28389a62069cee31882dcae4a4e10383e4518f2/src/binder/statement/create_table.rs#L90-L99
when we only type `a int primary key`, we will go to line 98 directly without setting `is_nullable` to false

**Comment by skyzh** [comment]
Just thought about the constraints in our system, I think we can allow primary key to be null. The storage layer should have fully supported it. But I'm not sure whether there are some places that assume primary key to be non-null.

From my perspective, it's okay to assume primary key to be non-null. When users type statements like `create table t(a int primary key, b int);`, or `create table t(a int, b int, primary key(a));`, we can by default make `a` a non-nullable column.

**Comment by skyzh** [comment]
Let's make this task clearer:

https://github.com/risinglightdb/risinglight/blob/acb624c58334c8be8039baccf83069eeb1578609/src/binder/statement/create_table.rs#L78-L89

When the binder binds a create table statement, here we should iterate all columns, and set those columns where `is_primary = true` to have a non-null datatype in `ColumnDesc`.

I think this task is easy enough, we can encourage community members to take this.
