### ISSUE TITLE
storage: select compaction strategy using statistics

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#638]
If we find distinct value statistics is very small compared with row counts, we can use RLE encoding when building RowSets.

https://github.com/risinglightdb/risinglight/blob/65372ee4da36bada718a6ab00cdba865ba554e5e/src/storage/secondary/compactor.rs#L93-L96

**Comment by jess-x** [comment]
newbie here, can I get this a try?

**Comment by noneback** [comment]
Any progress? I am also very interested in it.

**Comment by skyzh** [comment]
Hmm, maybe you can take over this as it has been nearly a month that we haven't heard back from @jess-x 🤣

**Comment by jess-x** [comment]
hi, feel free to take over. didn't have the bandwidth this past month 🥲
