### ISSUE TITLE
storage: support dict encoding

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#639]
... which should be similar to RLE encoding.

We can simply create a `DictIterator` wrapper over existing block iterators.

https://github.com/risinglightdb/risinglight/blob/main/src/storage/secondary/block/rle_block_iterator.rs

**Comment by Kikkon** [comment]
Let me have a try! 🤣

**Comment by Kikkon** [comment]
Hi！
I am working on this issue and have some doubts about it.
Do we need to build a complete dictionary for compression e.g.
```
Dict:[0 ⇒ A ,1 ⇒ B]
Encode : A B A A A B ⇒ 0 1 0 0 0 1  
```
encoding and decoding require build hashmap

Or do we compare the previous value directly. e.g.
```
Dict: [0 ⇒ A, 1 ⇒ B,  2 ⇒ A, 3⇒ B]
Encode : A B A A A B ⇒ 0 1 2 2 2 3 
```
so that encoding and decoding are very simple, 

@skyzh  Any other advice?

**Comment by skyzh** [comment]
The latter one looks exactly the same as run-length encoding, so maybe the former one looks better to me?

**Comment by Kikkon** [comment]
@skyzh  but item has already implemented` ?size,` can't use the map provided by the system lib, do I need to implement it myself?

**Comment by xxchan** [comment]
Where does `?Sized` become a problem? Can you show relevant code and compiler error?

**Comment by Kikkon** [comment]
I want to create a hashmap with key as Array::item, but the compiler tells me：
`the size for values of type `<A as array::Array>::Item` cannot be known at compilation time
the trait `Sized` is not implemented for `<A as array::Array>::Item``

**Comment by skyzh** [comment]
Yes. You can clone it.

**Comment by xxchan** [comment]
Try 
```rust
let mut m = HashMap::new();
m.insert(item.unwrap().to_owned(), 1);
```
And you can check the infered key type
