### ISSUE TITLE
use `ref-cast` for `BlobRef` cast

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#641]
https://github.com/dtolnay/ref-cast

Currently, we directly transmute these two types. We can use `ref-cast` crate to make it looks safer.

https://github.com/risinglightdb/risinglight/blob/acb624c58334c8be8039baccf83069eeb1578609/src/types/blob.rs#L99-L104

**Comment by Kikkon** [comment]
I'm a noob of rust, can I have a try?

**Comment by skyzh** [comment]
Thanks! Please have a try.
