### ISSUE TITLE
support column pruning for some operators

### ISSUE THREAD

**Issue by lokax** [risinglightdb/risinglight#654]
**Finished:**
- [x] Internal
- [x] logical_aggregate
- [x] logical_copy_to_file
- [x] logical_delete
- [x] logical_filter
- [x] logical_insert
- [x] logical_join
- [x] logical_limit
- [x] logical_order
- [x] logical_projection
- [x] logical_table_scan
- [x] logical_top_n
- [x] logical_values

**Comment by xxchan** [comment]
some == all? 😄
