### ISSUE TITLE
binder: separate InputRef to another expression type

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#693]
InputRef should not be part of `BoundExpression`. We should have a separate enum for planner expression, which don't have ColumnRef but have InputRef.

**Comment by wangrunji0408** [comment]
This issue become obsolete after we introduced the new planner.

However, in the new planner we still have both types defined in the same enum ([code](https://github.com/risinglightdb/risinglight/blob/52ee8ce5a01f6f69243164e5d8c99d01b237ba77/src/planner/mod.rs#L28-L30)). But now we guarantee that `InputRef` will only be used by executors and will never appear during optimization.
