### ISSUE TITLE
doc: deep(er) dive into storage

### ISSUE THREAD

**Issue by yinfredyue** [risinglightdb/risinglight#697]
We can have a more detailed (than the storage overview) doc for storage layer. 

### Why?

The storage overview doc is a good one and introduces many key components of the storage layer. But I believe we can have another doc that goes into more detail, for the following reasons:

- The storage doc only very briefly mentions the crucial components but does not go into details (that are enough to easily trace through the code).

- The storage doc talks very little about the distinction between in-memory representation and on-disk representation, and how such conversions happen. Structs like `ArrayImpl`, `Rowset`, and `ColumnBuilder` are certainly worth a more detailed explanation.

- This could be a starting point for the long-awaited storage sections of `risinglight-tutorial` ;)

### How?

I think it's a good idea to walk through an example of inserting one row into a table and explain (hopefully) everything that must be done to make the insertion happen. Topics include: in-memory representation `ArrayImpl`, `DataChunk`; `SecondaryMemRowset` vs. `Diskrowset`; `Block`, `BlockBuilder`, and `BlockIndexBuilder`.

### Plan

If this looks good, I can do the first draft.

**Comment by Daniel-Xu** [comment]
this is a long waited one!!!

**Comment by yinfredyue** [comment]
The first draft is finished. PTAL!
