### ISSUE TITLE
storage: bootstrap manifest replay

### ISSUE THREAD

**Issue by yinfredyue** [risinglightdb/risinglight#739]
When bootstrapping secondary storage, the manifest log is replayed to restore the internal state of `VersionManager`. This is done via the `commit_changes` call.

https://github.com/risinglightdb/risinglight/blob/365f2858099d856a6831eede1e75db1a5018a9b6/src/storage/secondary/storage.rs#L164

The problem with this is that any effective `AddRowset`/`AddDV` are written to the manifest file again at bootstrap. This means that, if the database keeps crashing and coming back, the manifest will keep growing (due to the bootstrap), even if no write happens.

Under the textbook WAL setting, redo&undo phase append more logs (and those logs provide useful information). But I don't think those logs are necessary/useful for RisingLight, because it's using a much simpler logging scheme.

**Comment by skyzh** [comment]
Yes! My idea is to periodically take a snapshot of the database and replace some of the manifest entries with snapshot.
