### ISSUE TITLE
Regarding setting up rust toolchain in development guide

### ISSUE THREAD

**Issue by 2010YOUY01** [risinglightdb/risinglight#758]
Hi,

Previously I tried to set up the project on OSX following https://github.com/risinglightdb/risinglight/blob/main/docs/00-develop.md but it failed to build.
Then I find the problem is I installed rust both in `brew` and `rustup`, and `brew uninstall rust` solved the problem. (`brew install rust; make check` might reproduce the problem)
Do you think we should suggest OSX users uninstall rust in `brew` first if they have installed it previously?

**Comment by xxchan** [comment]
It can also happen e.g. for users using `apt`. I don't think it necessary for us (or every rust project) to guide installing toolchain in such detailed way..
