### ISSUE TITLE
expr: avoid div by zero error when vectorization

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#773]
```
> create table t2(x int, y int);
+---+
| 1 |
+---+
in 0.045s
> insert into t2 values (1, 2), (2, null);
2023-02-08T05:38:29.126526Z  INFO risinglight::storage::secondary::transaction: RowSet #1 flushed, DV  flushed
+---+
| 2 |
+---+
in 0.050s
> select x / y from t2;
thread 'tokio-runtime-worker' panicked at 'attempt to divide by zero', /rustc/c1a859b25a95999ba276075bbd8e284ea675b41a/library/core/src/ops/arith.rs:488:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
++
++
in 0.018s
```

as `y = null` should yield null, it shouldn't be causing div by zero error.

One possible solution is to find if there's a way to div without exception.

**Comment by skyzh** [comment]
I feel div is not something that can be SIMDed, probably we should just add a if check.

**Comment by wangrunji0408** [comment]
I think it is possible since the SIMD operation can be masked at the instruction level. But I don't find a way to do masking by either using std::simd API or auto-vectorization. So I agree that we should bring the check back to fix this bug.
